postgres:
  host: "localhost"
  port: 5432
  database: "cosmos_fees"
  username: "postgres"
  password: "postgres"
  ssl: false
  pool_size: 10

server:
  port: "3000"

chains:
  cosmoshub-4:
    name: "cosmos"
    start_height: 29248064
    rpc_base_url:
      - "https://cosmos-rpc.polkachu.com"
    batch_size: 5
    retry_attempts: 3
    retry_delay_ms: 1000
  agoric:
    name: "agoric"
    start_height: 23674816
    rpc_base_url:
      - "https://agoric-rpc.polkachu.com"
    batch_size: 5
    retry_attempts: 3
    retry_delay_ms: 1000
